{
    "name": "Nextcloud Document Hub",
    "summary": "Upload CRM, Project, Task, Purchase, Delivery and Expense files to Nextcloud WebDAV",
    "version": "18.0.3.7.0",
    "category": "Productivity/Documents",
    "author": "Odoo Nextcloud Integration Contributors",
    "license": "LGPL-3",
    "depends": ["base", "web", "mail", "crm", "project", "purchase", "stock", "hr_expense"],
    "external_dependencies": {"python": ["requests"]},
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/nextcloud_category_data.xml",
        "data/nextcloud_activity_data.xml",
        "data/nextcloud_cron.xml",
        "views/nextcloud_document_views.xml",
        "views/nextcloud_management_views.xml",
        "views/res_config_settings_views.xml",
        "wizards/nextcloud_upload_wizard_views.xml",
        "wizards/nextcloud_rename_wizard_views.xml",
        "views/crm_lead_views.xml",
        "views/project_project_views.xml",
        "views/project_task_views.xml",
        "views/purchase_order_views.xml",
        "views/res_partner_views.xml",
        "views/stock_picking_views.xml",
        "views/hr_expense_views.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "odoo_nextcloud_document_hub/static/src/scss/hide_chatter_attachments.scss",
            "odoo_nextcloud_document_hub/static/src/js/hide_chatter_attachments.js",
        ],
    },
    "installable": True,
    "application": True,
}
